### ISSUE TITLE
confused about the doc_idx，when I split passage_ds and ds, doc_idxis vary large

### ISSUE THREAD

**Issue by zzk2021** [LinWeizheDragon/FLMR#13]
![image](https://github.com/LinWeizheDragon/FLMR/assets/73774678/3e9ac95a-ebdc-4352-bf5d-6bc69e26cba0)

I look into the code, I do not understand the doc_idx, is the tokenizer of query?
![image](https://github.com/LinWeizheDragon/FLMR/assets/73774678/110230a8-a1d0-43f8-ad7b-a3d1715e736e)

![image](https://github.com/LinWeizheDragon/FLMR/assets/73774678/2d54ab3c-0eb4-4716-a0a9-6ff383467496)
when I runing, it raises error.

**Comment by LinWeizheDragon** [comment]
`retrieved_docs` is returned by the ColBERT engine. doc[0] is the index of document that the engine retrieves.
The index refers to the index in `passage_contents`. For example, if the doc_id is 0, then the retrieved document is the first document in `passage_contents`.
You have out of range index possibly because you changed the corpus size `len(passage_contents)` but you haven't regenerate the index. You should delete the previously generated index files and rerun the script with `--run_indexing`.
