### ISSUE TITLE
difference between FLMR and PreFLMR implementations

### ISSUE THREAD

**Issue by dcaffo98** [LinWeizheDragon/FLMR#32]
Hi, thank you for releasing this amazing work.
I'm trying out the code for "[Index a custom document collection](https://github.com/LinWeizheDragon/FLMR?tab=readme-ov-file#index-a-custom-document-collection)" using the **_LinWeizheDragon/PreFLMR_ViT-G_** checkpoint and a (fictitious) multimodal collection, where documents images are just random floating point tensors (i.e. Option 3). I suppose that the following should load a PreFLMR model:
```
model = FLMRModelForRetrieval.from_pretrained(
    "LinWeizheDragon/PreFLMR_ViT-G",
    query_tokenizer=query_tokenizer,
    context_tokenizer=context_tokenizer,
)
```

However, when debugging into the `index_custom_collection` function, I reach the point where there happens the model forward, inside the [doc](https://github.com/LinWeizheDragon/FLMR/blob/9df9fa3731eb3f0770233949b8ff2b37ada96d90/flmr/models/flmr/modeling_flmr.py#L1240) method. But here is something about how you process images that I can't get. [L1313-1316](https://github.com/LinWeizheDragon/FLMR/blob/9df9fa3731eb3f0770233949b8ff2b37ada96d90/flmr/models/flmr/modeling_flmr.py#L1313) takes the [CLS] token from the vision encoder, runs it through a feed-forward network (i.e. the mapping network), and finally chunks it into several embeddings of size 128. Taking only the [CLS] visual token looks more like how FLMR processes images, because the PreFLMR paper (Sec. 4) states that 

> ...  (2) We introduce Transformer blocks with cross-attention into
> the mapping structure to obtain query-aware visual
> representation. The Transformer blocks take the
> image patch embeddings as input, and use crossattention to integrate the features of the text encoder. This allows PreFLMR to attend to different aspects of the image under different queries.
> These Transformer blocks are placed in parallel
> with FLMR’s 2-layer MLP mapping structure.

I don't understand where these Transformers blocks with cross-attention are found in the **_LinWeizheDragon/PreFLMR_ViT-G_** checkpoint.

**Comment by LinWeizheDragon** [comment]
The transformer mapping is only used for queries. In document encoding, only linear mapping is used.

This is because, at the time of this study, there lacks large-scale retrieval datasets that have both multi-modal queries and documents. As a result, we trained the system with multi-modal queries and text-only documents, and then leveraged the techniques mentioned in the FLMR paper's appendix to directly reuse the linear mapping at the query side when generating embeddings for documents. This arises from the fact that if the query image and document image are similar, they are naturally aligned in the feature space, leading to high retrieval scores under the late-interaction setting. However, this can be viewed as an experimental feature and the performance is suboptimal. 

If you do need highly performing multi-modal corpus support, you can train the system on your own multi-modal datasets and use the function we provided to index multi-modal documents.
